# Generated by Django 6.0 on 2026-03-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
